version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
  test:
    build: .
    command: pytest --maxfail=1 --disable-warnings
    env_file:
      - .env 